### ISSUE TITLE
Not working with ESP32 C3

### ISSUE THREAD

**Issue by Skywalkerf34** [FastLED/FastLED#1389] opened 2022-05-09 15:36 UTC
Hi,

I can compile but the result is lighting 2812 LED out of control
I suspect this is "just" timer issue as ESP32 C3 is 160mhz CPU
Can you give me some ways to change and try to fix this ?

Rgds

**Comment by s-light** [comment] 2022-06-21 14:47
do you use wifi at the same time?
could be a duplicate of #1349

**Comment by Skywalkerf34** [comment] 2022-06-21 15:40
yes I use wifi

**Comment by s-light** [comment] 2022-06-21 15:42
try to temporarily disable wifi - just to be sure its the same bug as #1349.

**Comment by samguyer** [comment] 2022-11-25 21:48
@Skywalkerf34 How's it going? Do you still need support, or can we close this issue?

**Closed** 2022-11-26 05:11 UTC
